# Numpy

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.4


In [3]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
#Same data type in array
arr = np.array([1,2,'A'])
print(arr)

['1' '2' 'A']


In [11]:
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


## Dimensions

In [71]:
# 0-D arrays
arr = np.array(33)
print(arr)
print(arr.ndim)

33
0


In [73]:
# 1-D array
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.ndim)

[1 2 3 4 5]
1


In [75]:
# 2-D array
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print(arr.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2


In [77]:
# 3-D array
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10, 11, 12]]])
print(arr)
print(arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


### Array Indexing

In [28]:
arr = np.array([1,2,3,4,5,6])
print(arr[0])
print(arr[-1])
print(arr[0:5])

1
6
[1 2 3 4 5]


In [32]:
print((arr[1] * arr[2]) > arr[4])

True


In [46]:
arr = np.array([1,2,3,4,5,6])
arr[0] = 100
print(arr)
print(arr[0])

[100   2   3   4   5   6]
100


In [54]:
arr = np.array([1,2,3,4,5,6])
result = np.insert(arr, 1, 10)
print(result)

[ 1 10  2  3  4  5  6]


### Arange

In [57]:
arr = np.arange(start = 1, stop = 10, step = 3)
print(arr)

[1 4 7]


In [63]:
arr2 = np.arange(10)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]


In [69]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.ndim)

2


In [83]:
arr = np.array([1,2,3,4], ndmin = 10)
print(arr)

[[[[[[[[[[1 2 3 4]]]]]]]]]]


In [93]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0][2])
print(arr[0, 2])
print(arr[-1][-1])
print(arr[-1, -1])

3
3
10
10


In [99]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
result = np.insert(arr, 6, 11)
print(result)

[ 1  2  3  4  5  6 11  7  8  9 10]


In [121]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
result = np.insert(arr, 1, 11, axis = 1)
print(result)

[[ 1 11  2  3  4  5]
 [ 6 11  7  8  9 10]]


In [129]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
result = np.insert(arr, 1, 11, axis = 0)
print(result)

[[ 1  2  3  4  5]
 [11 11 11 11 11]
 [ 6  7  8  9 10]]


In [153]:
arr = np.array([(1,2,3), (4,5,6), (7,8,9), (50,51,52)])
print(arr)
print("***************************")
result = np.insert(arr, 1, [40, 100, 101], axis = 0)
print(result)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [50 51 52]]
***************************
[[  1   2   3]
 [ 40 100 101]
 [  4   5   6]
 [  7   8   9]
 [ 50  51  52]]


In [151]:
arr = np.array([(1,2,3), (4,5,6), (7,8,9), (50,51,52)])
print(arr)
print("**********************")
result = np.insert(arr, 1, [40, 100, 101, 111], axis = 1)
print(result)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [50 51 52]]
***************************
[[  1  40   2   3]
 [  4 100   5   6]
 [  7 101   8   9]
 [ 50 111  51  52]]


In [159]:
for i in arr:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]
[50 51 52]


In [161]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr.shape)

(2, 5)


In [173]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
result = arr.reshape(4,3)
print(result)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [169]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
result = arr.reshape(2,3,2)
print(result)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [179]:
arr = np.array([1,2,3,4,5,6,7,8])
result = arr.reshape(2, 4)
print(result)

[[1 2 3 4]
 [5 6 7 8]]


In [181]:
arr = np.array([1,2,3,4,5,6,7,8])
result = arr.reshape(4, 2)
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [183]:
arr = np.array([1,2,3,4,5,6,7,8])
result = arr.reshape(3, 3)
print(result)

ValueError: cannot reshape array of size 8 into shape (3,3)

### Auto adjust dimentions

In [198]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
result = arr.reshape(2,2,-1)
print(result)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [196]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
result = arr.reshape(-1)
print(result)

[ 1  2  3  4  5  6  7  8  9 10]


### Slicing

In [243]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])
print(arr[0:2])
print(arr[0:2, 3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[4 9]


In [247]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])
print(arr[0:2])
print(arr[0:2, 1:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[2 3]
 [7 8]]


In [245]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])
print(arr[1])
print(arr[1, 1:4])

[ 6  7  8  9 10]
[7 8 9]


### np.zeros

In [252]:
x = np.zeros(2)
print(x)

[0. 0.]


In [286]:
x = np.zeros(2, dtype = int)
print(x)

[0 0]


In [288]:
x = np.zeros(2, dtype = str)
print(x)
print(x.dtype)

['' '']
<U1


In [290]:
x = np.zeros([2,5], dtype = int)
print(x)
print(x.dtype)

[[0 0 0 0 0]
 [0 0 0 0 0]]
int32


### np.ones

In [276]:
x = np.ones(4)
print(x)

[1. 1. 1. 1.]


In [278]:
x = np.ones(4, dtype=int)
print(x)

[1 1 1 1]


In [280]:
x = np.ones(4, dtype=str)
print(x)

['1' '1' '1' '1']


### np.arange

In [269]:
x = np.arange(4)
print(x)

[0 1 2 3]


In [271]:
x = np.arange(1, 10, 2)
print(x)

[1 3 5 7 9]


In [296]:
arr = np.array([1,2,3,4,5], dtype = "S")
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [298]:
arr = np.array(['a', '2', '3'], dtype = 'i')
print(arr)


ValueError: invalid literal for int() with base 10: 'a'

#### Convert dtype of existing array

In [305]:
arr = np.array([1.2, 2.3, 3.4])
result = arr.astype('i')
print(result)
print(result.dtype)

[1 2 3]
int32
